#
# Simple Makefile
#
# Author: Dennis Koslowski <dennis.koslowski@gmx.de>
# Date:   2020-01-13
#

OBJS = color_conversion.o
CFLAGS = -Wall
CXXFLAGS= -Wall

default: $(OBJS)

clean:
	rm -f $(OBJS) *~
